### ISSUE TITLE
Ich hab das internet kaputt gemacht

### ISSUE THREAD

**Issue by B44K** [AEO-LkInf17/AEO-Planer#2]

**Comment by felix9082** [comment]
system 32 ordner löschen

**Comment by Fruechtetee** [comment]
Du muss einen Eimer Wasser über den Pc kippen, dann geht das sc hon wieder!

**Comment by B44K** [comment]
hab ich schon versucht jetzt geht nur noch mein auto bildschirm

**Comment by Fruechtetee** [comment]
So hats zumindestens bei mir geklappt

**Comment by dawidk25** [comment]
alt f4

**Comment by B44K** [comment]
koole sache

**Comment by dawidk25** [comment]
nibba

**Comment by B44K** [comment]
alt x3
